//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury.Language.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JapaneseEra {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JapaneseEra() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mercury.Language.Extensions.Properties.JapaneseEra", typeof(JapaneseEra).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1868-09-08.
        /// </summary>
        internal static string Era1 {
            get {
                return ResourceManager.GetString("Era1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999-12-31.
        /// </summary>
        internal static string Era10 {
            get {
                return ResourceManager.GetString("Era10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1912-07-30.
        /// </summary>
        internal static string Era2 {
            get {
                return ResourceManager.GetString("Era2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1926-12-25.
        /// </summary>
        internal static string Era3 {
            get {
                return ResourceManager.GetString("Era3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1989-01-08.
        /// </summary>
        internal static string Era4 {
            get {
                return ResourceManager.GetString("Era4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-05-01.
        /// </summary>
        internal static string Era5 {
            get {
                return ResourceManager.GetString("Era5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999-12-31.
        /// </summary>
        internal static string Era6 {
            get {
                return ResourceManager.GetString("Era6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999-12-31.
        /// </summary>
        internal static string Era7 {
            get {
                return ResourceManager.GetString("Era7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999-12-31.
        /// </summary>
        internal static string Era8 {
            get {
                return ResourceManager.GetString("Era8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999-12-31.
        /// </summary>
        internal static string Era9 {
            get {
                return ResourceManager.GetString("Era9", resourceCulture);
            }
        }
    }
}
